version: '3.9'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass

  wordpress:
    container_name: my-wp-container
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./html:/var/www/html #wordpressファイル群格納用
      - ./wp-content:/var/www/html/wp-content #テーマ、プラグイン開発用
      - ./**my-theme**:/var/www/html/wp-content/themes/**my-theme** #オリジナルテーマ開発用空テーマ**my-theme**部分は適宜変更。
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root-pass
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - "8080:80"
  # sqlファイルインポート時はファイルサイズの上限を変更するためコメントアウトを外す
  # volumes:
  #    - ./phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini

volumes:
    db_data: {}
